import type { EventRecord } from "@/lib/flexible/model";
import { ActionForm, Confirm, SendButton } from "./form";

export function Communities({ event }: { event: EventRecord }) {
  return <section className="neo-panel"><div className="neo-section-heading"><h2>Komunitas / sektor</h2><span className="neo-count">{event.data.communities.length}</span></div>
    <p className="neo-hint">Perubahan nama atau penggabungan memperbarui komunitas peserta tanpa mengubah pembagian meja dan skor yang sudah tersimpan.</p>
    <ActionForm eventId={event.id} version={event.version} operation="community-create" resetOnSuccess><label>Nama komunitas / sektor<input name="name" minLength={2} maxLength={80} required /></label><SendButton>Daftarkan komunitas</SendButton></ActionForm>
    <div className="neo-community-list">{event.data.communities.map(item => { const count = event.data.participants.filter(person => person.communityId === item.id).length; return <details key={item.id}><summary><strong>{item.name}</strong><span>{count} peserta · Kelola</span></summary><div className="neo-community-actions"><ActionForm eventId={event.id} version={event.version} operation="community-update"><input type="hidden" name="communityId" value={item.id} /><label>Ubah nama<input name="name" defaultValue={item.name} required maxLength={80} /></label><SendButton secondary>Simpan nama</SendButton></ActionForm><ActionForm eventId={event.id} version={event.version} operation="community-merge"><input type="hidden" name="communityId" value={item.id} /><label>Gabungkan ke<select name="targetCommunityId" required defaultValue=""><option value="" disabled>Pilih komunitas tujuan</option>{event.data.communities.filter(other => other.id !== item.id).map(other => <option key={other.id} value={other.id}>{other.name}</option>)}</select></label><Confirm>Pindahkan {count} peserta ke komunitas tujuan dan hapus komunitas ini.</Confirm><SendButton secondary>Gabungkan komunitas</SendButton></ActionForm>{count === 0 ? <ActionForm eventId={event.id} version={event.version} operation="community-delete"><input type="hidden" name="communityId" value={item.id} /><Confirm>Hapus komunitas kosong ini.</Confirm><SendButton secondary>Hapus komunitas</SendButton></ActionForm> : <p className="neo-notice">Komunitas berisi peserta tidak dapat langsung dihapus. Gabungkan ke komunitas lain terlebih dahulu.</p>}</div></details>; })}</div>
    {event.data.communities.length === 0 && <p className="neo-empty-small">Belum ada komunitas / sektor. Impor file juga dapat membuatnya otomatis.</p>}
  </section>;
}
