"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { communityName, reviewDraw, type EventRecord } from "@/lib/flexible/model";
import { ActionForm, Confirm, SendButton } from "./form";

function GenerateActions({ event, round, disabled = false, compact = false }: { event: EventRecord; round: number; disabled?: boolean; compact?: boolean }) {
  return <div className="neo-actions"><ActionForm eventId={event.id} version={event.version} operation="generate" round={round}><SendButton secondary={compact} disabled={disabled}>{compact ? "↻ Acak ulang" : "Generate acak"}</SendButton></ActionForm>{event.data.parentId && <ActionForm eventId={event.id} version={event.version} operation="generate-seeded" round={round}><SendButton secondary disabled={disabled}>{compact ? "↻ Bagi adil ulang" : "Bagi adil dari peringkat"}</SendButton></ActionForm>}</div>;
}

export function DrawBoard({ event, selected }: { event: EventRecord; selected: number }) {
  const [query, setQuery] = useState("");
  const router = useRouter();
  const { settings, participants, draws } = event.data;
  const draw = draws.find(item => item.number === selected);
  const previous = draws.filter(item => item.number < selected && item.locked);
  const ready = participants.length === settings.target && previous.length === selected - 1;
  const people = new Map(participants.map(person => [person.id, person]));
  const review = draw ? reviewDraw(draw.tables, participants, previous) : null;
  const lockedLater = draws.some(item => item.number > selected && item.locked);
  const visible = draw?.tables.map((table, index) => ({ table, number: index + 1 })).filter(({ table, number }) => !query || String(number) === query || table.some(id => { const person = people.get(id); return person && `${person.number} ${person.name} ${communityName(event.data, person)}`.toLowerCase().includes(query.toLowerCase()); }));

  return <><div className="neo-round-tabs" aria-label="Pilih babak">{Array.from({ length: settings.rounds }, (_, index) => { const number = index + 1; const current = draws.find(item => item.number === number); return <Link key={number} href={`?round=${number}`} aria-current={selected === number ? "page" : undefined} className={selected === number ? "selected" : ""}><span>Babak {String(number).padStart(2, "0")}</span><small>{current?.locked ? "✓ Dikunci" : current ? "Draft" : "Belum dibuat"}</small></Link>; })}</div>
    <div className="neo-section-heading"><div><span className={`neo-tag ${draw?.locked ? "neo-green" : "neo-blue"}`}>{draw?.locked ? "PEMBAGIAN DIKUNCI" : "RUANG REVIEW"}</span><h2>Babak {selected} <small>/ {settings.rounds}</small></h2></div><span className="neo-hint">{draw ? `Revisi ${draw.revision} · ${draw.tables.length} meja · ${draw.generation === "seeded" ? "Berdasarkan peringkat" : "Acak"}` : "Skor tidak diperlukan"}</span></div>
    {!draw ? <section className="neo-empty"><span className="neo-empty-symbol" aria-hidden="true">♠</span><h3>Mejanya belum disusun.</h3><p>{ready ? event.data.parentId ? "Pilih pembagian acak atau pembagian adil berdasarkan peringkat dari tahap sebelumnya." : "Generate pembagian yang mempertimbangkan komunitas dan pertemuan sebelumnya." : participants.length !== settings.target ? "Lengkapi daftar nama atau sesuaikan target peserta sebelum membuat pembagian." : "Kunci pembagian babak sebelumnya terlebih dahulu. Pertandingannya tidak perlu dimulai."}</p><GenerateActions event={event} round={selected} disabled={!ready} /></section> : <>
      <div className="neo-draw-toolbar"><label className="neo-search">Cari meja atau peserta<input type="search" value={query} onChange={input => setQuery(input.target.value)} placeholder="Nama, nomor peserta, atau meja…" /></label>{!draw.locked && <GenerateActions event={event} round={selected} compact />}<button className="neo-button neo-secondary" type="button" onClick={() => router.refresh()}>Muat ulang</button></div>
      {event.data.parentId && !draw.locked && <p className="neo-notice"><strong>Mode adil:</strong> peserta dibagi dalam pot peringkat. Peringkat atas ditempatkan di meja berbeda, kemudian sistem menyeimbangkan pot berikutnya sambil mengurangi pertemuan ulang.</p>}
      {review && <div className="neo-notice" role="status"><strong>Review rotasi:</strong> {review.repeats} pertemuan berulang · {review.sameCommunity} pasangan satu komunitas.{review.penalty === 0 ? " Tidak ada konflik terdeteksi." : " Periksa susunan; pembagian sempurna mungkin tidak tersedia untuk komposisi peserta ini."}{draw.tables.some(table => table.length < settings.capacity) && " Ada meja tidak penuh; jumlah pemain sudah diseimbangkan."}</div>}
      <div className="neo-tables">{visible?.map(({ table, number }) => <article className="neo-table" key={number}><header><h3>MEJA <b>{String(number).padStart(2, "0")}</b></h3><span>{table.length}/{settings.capacity} orang</span></header><ol>{table.map((id, index) => { const person = people.get(id); return <li key={id}><span className="neo-seat">{index + 1}</span><div><strong>{person?.name ?? "Peserta tidak ditemukan"}</strong><small>#{person?.number} · {person ? communityName(event.data, person) || "Tanpa komunitas" : ""}</small></div></li>; })}</ol></article>)}</div>{visible?.length === 0 && <p className="neo-empty-small">Tidak ada meja atau nama yang cocok.</p>}
      {!draw.locked ? <div className="neo-two-col"><section className="neo-panel"><h3>Tukar peserta</h3><p>Pilih dua nama. Posisi meja dan kursinya akan ditukar, tanpa mengganti identitas.</p><ActionForm eventId={event.id} version={event.version} operation="swap" round={selected}><div className="neo-fields">{["first", "second"].map((field, index) => <label key={field}>Peserta {index + 1}<select name={field} required defaultValue=""><option value="" disabled>Pilih peserta…</option>{draw.tables.flatMap((table, tableIndex) => table.map(id => <option value={id} key={id}>Meja {tableIndex + 1} · #{people.get(id)?.number} {people.get(id)?.name}</option>))}</select></label>)}</div><SendButton secondary>Tukar posisi</SendButton></ActionForm></section><section className="neo-panel neo-yellow"><h3>Sudah cocok? Kunci pembagiannya.</h3><p>Kunci hanya menyimpan susunan meja. Setelah itu, Anda bisa menyiapkan babak berikutnya tanpa skor.</p><ActionForm eventId={event.id} version={event.version} operation="lock" round={selected}><Confirm>Saya sudah memeriksa peserta dan peringatan rotasi. Pembagian ini boleh tampil pada link publik yang aktif.</Confirm><SendButton>Kunci pembagian babak {selected}</SendButton></ActionForm></section></div> : <section className="neo-panel neo-locked"><div><h3>✓ Susunan aman. Siap dimainkan.</h3><p>Masukkan skor saat meja selesai bermain. Persiapan babak berikutnya tetap dapat dilakukan lebih dahulu.</p><div className="neo-actions"><Link href={`/tournaments/${event.id}/game?round=${selected}`} className="neo-button neo-dark">Input skor babak {selected} →</Link>{selected < settings.rounds && <Link href={`?round=${selected + 1}`} className="neo-button">Siapkan babak {selected + 1} →</Link>}</div></div><details className="neo-disclosure"><summary>Perlu koreksi pembagian?</summary>{lockedLater ? <p>Buka kunci dari babak terakhir terlebih dahulu.</p> : <ActionForm eventId={event.id} version={event.version} operation="unlock" round={selected}><Confirm>Tarik babak ini dari link publik dan buang draft berikutnya. Saya akan memberi tahu peserta jika jadwal berubah.</Confirm><SendButton secondary>Buka kunci untuk koreksi</SendButton></ActionForm>}</details></section>}
    </>}
  </>;
}
