import Link from "next/link";
import type { EventRecord } from "@/lib/flexible/model";
import { communityName } from "@/lib/flexible/model";
import { resultFor } from "@/lib/flexible/scoring";
import { ActionForm, Confirm, SendButton } from "./form";

export function GameBoard({ event, selected }: { event: EventRecord; selected: number }) {
  const draw = event.data.draws.find(item => item.number === selected && item.locked);
  const people = new Map(event.data.participants.map(person => [person.id, person]));
  const locked = Boolean(event.data.qualificationLockedAt);
  return <><div className="neo-round-tabs" aria-label="Pilih babak">{Array.from({ length: event.data.settings.rounds }, (_, index) => { const number = index + 1; const roundDraw = event.data.draws.find(item => item.number === number && item.locked); const completed = roundDraw?.tables.filter((_, tableIndex) => resultFor(event.data, number, tableIndex + 1)).length ?? 0; return <Link key={number} href={`?round=${number}`} className={selected === number ? "selected" : ""}><span>Babak {String(number).padStart(2, "0")}</span><small>{roundDraw ? `${completed}/${roundDraw.tables.length} meja masuk` : "Belum dikunci"}</small></Link>; })}</div>
    {locked && <p className="neo-notice neo-success">Kelolosan sudah dikunci. Skor ditampilkan sebagai arsip dan tidak dapat diubah.</p>}
    {!draw ? <section className="neo-empty"><h2>Pembagian belum dikunci.</h2><p>Kunci pembagian babak ini sebelum memasukkan skor.</p><Link className="neo-button" href={`/tournaments/${event.id}/draws?round=${selected}`}>Buka pembagian →</Link></section> : <div className="neo-score-grid">{draw.tables.map((table, tableIndex) => { const tableNumber = tableIndex + 1; const result = resultFor(event.data, selected, tableNumber); const scores = new Map(result?.scores.map(score => [score.participantId, score])); return <article className={`neo-panel neo-score-card ${result ? "is-complete" : ""}`} key={tableNumber}><div className="neo-section-heading"><div><span className={`neo-tag ${result ? "neo-green" : "neo-blue"}`}>{result ? "SUDAH MASUK" : "BELUM DIISI"}</span><h2>Meja {String(tableNumber).padStart(2, "0")}</h2></div>{result && <span className="neo-count">✓</span>}</div><ActionForm eventId={event.id} version={event.version} operation="score-table" round={selected}><input type="hidden" name="table" value={tableNumber} /><div className="neo-score-list">{table.map(participantId => { const person = people.get(participantId); const score = scores.get(participantId); return <div className="neo-score-row" key={participantId}><div><strong>{person?.name}</strong><small>#{person?.number} · {person ? communityName(event.data, person) || "Tanpa komunitas" : ""}</small>{score && <span className="neo-rank">Peringkat {score.tableRank} · {score.tournamentPoint} poin</span>}</div><label>Skor<input name={`score-${participantId}`} type="number" required defaultValue={score?.score ?? ""} disabled={locked} /></label><label>Urutan seri <small>hanya jika skor sama</small><input name={`rank-${participantId}`} type="number" min="1" max={table.length} disabled={locked} /></label></div>; })}</div>{!locked && <SendButton>{result ? "Perbarui skor meja" : "Simpan skor meja"}</SendButton>}</ActionForm>{result && !locked && <details className="neo-disclosure"><summary>Hapus hasil meja</summary><ActionForm eventId={event.id} version={event.version} operation="score-clear" round={selected}><input type="hidden" name="table" value={tableNumber} /><Confirm>Hapus seluruh skor meja ini untuk diisi ulang.</Confirm><SendButton secondary>Hapus skor</SendButton></ActionForm></details>}</article>; })}</div>}
  </>;
}
