import Link from "next/link";

const flow = [
  ["01", "Buat turnamen", "Tentukan nama, target peserta, kapasitas meja, jumlah babak, dan jumlah peserta yang lolos."],
  ["02", "Siapkan peserta", "Tambahkan nama dan komunitas secara manual atau melalui impor file."],
  ["03", "Susun meja", "Pilih Shuffle Rotasi atau Shuffle Tier, periksa susunan, lalu kunci pembagian."],
  ["04", "Main & catat skor", "Masukkan skor akhir setiap meja. Jika skor sama, tentukan urutan finisnya."],
  ["05", "Kunci hasil", "Setelah semua meja masuk, kunci hasil babak agar dapat dipakai Shuffle Tier berikutnya."],
  ["06", "Ulangi babak", "Lanjutkan pembagian, pertandingan, dan penguncian sampai seluruh babak selesai."],
  ["07", "Kunci kelolosan", "Periksa klasemen, kunci peserta lolos, lalu buat tahap lanjutan bila diperlukan."],
];

const features = [
  { title: "Peserta & komunitas", copy: "Kelola nomor peserta, nama, serta komunitas atau sektor. Sistem menggunakan komunitas untuk membantu mengurangi pertemuan satu kelompok.", buttons: ["+ Tambah peserta", "Impor peserta", "Kelola komunitas"] },
  { title: "Pembagian meja", copy: "Sistem membagi peserta semerata mungkin, menampilkan konflik yang masih tersisa, dan menyediakan pertukaran manual sebelum dikunci.", buttons: ["↻ Shuffle Rotasi", "◆ Shuffle Tier", "Kunci pembagian"] },
  { title: "Pertandingan", copy: "Panitia memasukkan skor per meja. Hasil dapat diperbaiki selama hasil babak belum dikunci.", buttons: ["Simpan skor meja", "Kunci hasil babak"] },
  { title: "Klasemen & publikasi", copy: "Klasemen dihitung otomatis. Jadwal meja dan klasemen dapat dibagikan melalui link publik baca-saja tanpa akses admin.", buttons: ["Buka klasemen", "Buat link pembagian", "Buat link klasemen"] },
];

export default function GuidePage() {
  return <>
    <Link className="neo-back" href="/tournaments">← Daftar turnamen</Link>
    <header className="neo-guide-hero"><div><span className="neo-tag neo-blue">PANDUAN PANITIA</span><h1>Cara kerja REMI,<br /><span>dari persiapan sampai selesai.</span></h1><p>Halaman ini menjelaskan fitur, urutan kerja, dan aturan permainan yang dihitung oleh sistem. Bacanya bisa dari awal, atau langsung pilih bagian yang dibutuhkan.</p><div className="neo-actions"><a className="neo-button" href="#alur">Mulai dari alur utama ↓</a><Link className="neo-button neo-secondary" href="/tournaments/new">Buat turnamen →</Link></div></div><aside><span className="neo-eyebrow">INTI SISTEM</span><strong>Susun meja.<br />Catat skor.<br />Kunci hasil.<br />Ulangi.</strong><small>Data baru dianggap resmi setelah panitia menekan tombol kunci yang sesuai.</small></aside></header>

    <nav className="neo-guide-nav" aria-label="Daftar isi panduan"><a href="#fitur">Fitur</a><a href="#alur">Alur pertandingan</a><a href="#shuffle">Jenis shuffle</a><a href="#meja">Pembagian meja</a><a href="#poin">Poin & klasemen</a><a href="#kunci">Sistem kunci</a><a href="#publik">Link publik</a></nav>

    <section className="neo-guide-section" id="fitur"><div className="neo-guide-heading"><span>01</span><div><p className="neo-eyebrow">GAMBARAN UMUM</p><h2>Apa saja yang bisa dilakukan?</h2><p>Contoh tombol di bawah dibuat menyerupai tampilan asli agar mudah dikenali ketika mulai mengoperasikan turnamen.</p></div></div><div className="neo-guide-features">{features.map((feature, index) => <article key={feature.title}><div className="neo-guide-feature-number">0{index + 1}</div><div><h3>{feature.title}</h3><p>{feature.copy}</p><div className="neo-guide-demo-actions" aria-label={`Contoh tombol ${feature.title}`}>{feature.buttons.map((button, buttonIndex) => <span className={`neo-guide-demo-button ${buttonIndex === 0 ? "is-primary" : ""}`} key={button}>{button}</span>)}</div></div></article>)}</div></section>

    <section className="neo-guide-section" id="alur"><div className="neo-guide-heading"><span>02</span><div><p className="neo-eyebrow">ALUR UTAMA</p><h2>Urutan kerja panitia</h2><p>Ikuti urutan ini untuk setiap turnamen. Babak berikutnya dapat disiapkan lebih awal dengan Shuffle Rotasi, atau menunggu hasil jika ingin memakai Shuffle Tier.</p></div></div><ol className="neo-guide-flow">{flow.map(([number, title, copy], index) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div>{index < flow.length - 1 && <b aria-hidden="true">→</b>}</li>)}</ol></section>

    <section className="neo-guide-section" id="shuffle"><div className="neo-guide-heading"><span>03</span><div><p className="neo-eyebrow">PEMBAGIAN OTOMATIS</p><h2>Dua jenis shuffle</h2><p>Keduanya tetap menghasilkan jumlah pemain yang merata. Perbedaannya adalah informasi yang menjadi prioritas sistem.</p></div></div><div className="neo-guide-compare"><article><span className="neo-tag neo-blue">FLEKSIBEL</span><h3>↻ Shuffle Rotasi</h3><p>Cocok ketika panitia ingin menyiapkan beberapa babak sejak awal.</p><ul><li>Tidak membutuhkan skor babak sebelumnya.</li><li>Pembagian sebelumnya harus sudah dikunci.</li><li>Prioritas utama: mengurangi pertemuan ulang.</li><li>Jika memungkinkan, peserta satu komunitas dipisahkan.</li></ul><div className="neo-guide-use"><strong>Gunakan ketika:</strong><span>jadwal perlu disiapkan lebih awal.</span></div></article><article className="is-tier"><span className="neo-tag neo-yellow-tag">KOMPETITIF</span><h3>◆ Shuffle Tier</h3><p>Cocok untuk mempertemukan peserta dengan hasil babak terakhir yang sebanding.</p><ul><li>Hanya tersedia mulai Babak 2.</li><li>Semua skor babak sebelumnya harus lengkap dan hasilnya dikunci.</li><li>P1–P2 menjadi kelompok <strong>Top</strong>; P3–P5 menjadi kelompok <strong>Pengejar</strong>.</li><li>P1 dan P2 dari meja asal yang sama dipisahkan.</li><li>P3 menjadi pengisi pertama jika meja campuran diperlukan.</li><li>Komunitas tetap dipertimbangkan setelah aturan tier.</li></ul><div className="neo-guide-use"><strong>Gunakan ketika:</strong><span>pertandingan ingin dibuat lebih kompetitif berdasarkan hasil terakhir.</span></div></article></div>
      <div className="neo-guide-tier-example"><div><span className="neo-eyebrow">CONTOH ASAL BABAK 1</span><h3>Top 2 dari meja yang sama</h3><div className="neo-guide-origin"><span><b>MEJA 07</b><em>P1 · Andi</em><em>P2 · Budi</em></span><strong aria-hidden="true">→</strong><span><b>BABAK 2</b><em>Andi · Meja 01</em><em>Budi · Meja 02</em></span></div></div><div className="neo-guide-player-tags"><span>TOP · P1 · MEJA 07 · BABAK 1</span><span>TOP · P2 · MEJA 07 · BABAK 1</span><small>Label pada peserta menunjukkan peringkat, meja asal, dan babak sumber sehingga pemisahannya dapat diperiksa langsung.</small></div></div>
    </section>

    <section className="neo-guide-section" id="meja"><div className="neo-guide-heading"><span>04</span><div><p className="neo-eyebrow">KAPASITAS</p><h2>Meja selalu dibagi merata</h2><p>Kapasitas maksimal adalah lima orang. Jika jumlah peserta tidak pas, sistem menambah meja lalu membagi pemain dengan selisih maksimal satu orang.</p></div></div><div className="neo-guide-table-examples"><article><span>6 PESERTA</span><div><b>MEJA 01<small>3 orang</small></b><b>MEJA 02<small>3 orang</small></b></div><p>Bukan 5–1.</p></article><article><span>12 PESERTA</span><div><b>MEJA 01<small>4 orang</small></b><b>MEJA 02<small>4 orang</small></b><b>MEJA 03<small>4 orang</small></b></div><p>Bukan 5–5–2.</p></article><article><span>16 PESERTA</span><div><b>MEJA 01<small>4 orang</small></b><b>MEJA 02<small>4 orang</small></b><b>MEJA 03<small>4 orang</small></b><b>MEJA 04<small>4 orang</small></b></div><p>Semua meja seimbang.</p></article></div><p className="neo-notice"><strong>Masih boleh dikoreksi:</strong> selama pembagian berstatus draft, panitia dapat menukar dua peserta secara manual. Setelah cocok, tekan <span className="neo-inline-button">Kunci pembagian</span>.</p></section>

    <section className="neo-guide-section" id="poin"><div className="neo-guide-heading"><span>05</span><div><p className="neo-eyebrow">SKOR & PERINGKAT</p><h2>Dari skor meja menjadi klasemen</h2><p>Skor menentukan urutan finis di meja. Urutan finis kemudian diubah menjadi poin turnamen.</p></div></div><div className="neo-guide-points">{[["P1", "5", "Juara meja"], ["P2", "4", "Posisi kedua"], ["P3", "3", "Posisi ketiga"], ["P4", "2", "Posisi keempat"], ["P5", "1", "Posisi kelima"]].map(([rank, point, label]) => <div key={rank}><span>{rank}</span><strong>{point}</strong><small>{label}<br />poin</small></div>)}</div><div className="neo-guide-score-layout"><article className="neo-panel"><span className="neo-eyebrow">CONTOH HASIL MEJA</span><h3>Skor lebih besar = posisi lebih tinggi</h3><ol><li><b>1</b><span>Nanda<small>Skor 850</small></span><strong>5 poin</strong></li><li><b>2</b><span>Raka<small>Skor 720</small></span><strong>4 poin</strong></li><li><b>3</b><span>Sari<small>Skor 610</small></span><strong>3 poin</strong></li></ol><p>Jika dua peserta memiliki skor sama, panitia wajib mengisi <strong>urutan seri</strong> agar posisi akhirnya tetap jelas.</p></article><article className="neo-panel neo-yellow"><span className="neo-eyebrow">MEJA KURANG DARI 5 ORANG</span><h3>Poin tetap dimulai dari 5</h3><p>Di meja berisi tiga orang, peringkatnya memperoleh 5, 4, dan 3 poin. Tidak ada poin tambahan yang dibagikan.</p></article></div>
      <div className="neo-guide-standing"><div className="neo-section-heading"><div><span className="neo-tag neo-blue">CONTOH</span><h3>Klasemen sementara</h3></div><span className="neo-hint">Data contoh</span></div><div className="neo-table-scroll"><table><thead><tr><th>Rank</th><th>Peserta</th><th>Main</th><th>🥇 Gold</th><th>🥈 Silver</th><th>🥉 Bronze</th><th>Poin</th><th>Total skor</th></tr></thead><tbody><tr><td><strong>1</strong></td><td><strong>Nanda</strong><small>#12 · Sektor 2</small></td><td>3/5</td><td>2</td><td>1</td><td>0</td><td><strong>14</strong></td><td>2.340</td></tr><tr><td><strong>2</strong></td><td><strong>Raka</strong><small>#31 · Sektor 5</small></td><td>3/5</td><td>2</td><td>0</td><td>1</td><td><strong>13</strong></td><td>2.410</td></tr><tr><td><strong>3</strong></td><td><strong>Sari</strong><small>#08 · Sektor 1</small></td><td>3/5</td><td>1</td><td>2</td><td>0</td><td><strong>13</strong></td><td>2.280</td></tr></tbody></table></div><p><strong>Urutan klasemen:</strong> total poin terbesar → total skor terbesar → jumlah medali Gold → Silver → Bronze. Nomor peserta tidak menentukan posisi.</p></div>
    </section>

    <section className="neo-guide-section" id="kunci"><div className="neo-guide-heading"><span>06</span><div><p className="neo-eyebrow">PENCEGAH KESALAHAN</p><h2>Ada dua kunci yang berbeda</h2><p>Ini bagian yang paling penting untuk dipahami. Mengunci meja tidak sama dengan mengunci hasil.</p></div></div><div className="neo-guide-locks"><article><span className="neo-tag neo-blue">SEBELUM MAIN</span><h3>1. Kunci pembagian</h3><p>Mengesahkan siapa bermain di meja mana dan membuat pembagian dapat tampil pada link peserta.</p><span className="neo-guide-demo-button is-primary">Kunci pembagian babak 2</span></article><b aria-hidden="true">→</b><article><span className="neo-tag neo-green">SETELAH MAIN</span><h3>2. Kunci hasil</h3><p>Mengesahkan skor dan posisi meja. Kunci inilah yang mengaktifkan Shuffle Tier babak berikutnya.</p><span className="neo-guide-demo-button is-dark">Kunci hasil babak 2</span></article></div><div className="neo-guide-rule-line"><span>DRAFT MEJA</span><b>→</b><span>PEMBAGIAN DIKUNCI</span><b>→</b><span>INPUT SKOR</span><b>→</b><span>HASIL DIKUNCI</span><b>→</b><span>SHUFFLE TIER AKTIF</span></div><p className="neo-notice"><strong>Perlu koreksi?</strong> Buka kunci dari bagian paling akhir. Jika pembagian Shuffle Tier turunan sudah dikunci, pembagian tersebut harus dibuka sebelum hasil sumbernya dapat dikoreksi.</p></section>

    <section className="neo-guide-section" id="publik"><div className="neo-guide-heading"><span>07</span><div><p className="neo-eyebrow">AKSES BACA-SAJA</p><h2>Dua link untuk kebutuhan berbeda</h2><p>Keduanya tidak memberi akses ke tombol admin. Link dapat diganti atau dicabut kapan saja.</p></div></div><div className="neo-guide-public"><article><span className="neo-tag">PESERTA</span><h3>Link pembagian meja</h3><p>Menampilkan nama, komunitas, serta meja pada babak yang pembagiannya sudah dikunci. Tidak menampilkan skor.</p><div className="neo-guide-url">/m/260917-143205</div><span className="neo-guide-demo-button is-primary">↓ Unduh PDF babak</span><small>PDF memuat identitas dan hyperlink GPIB Harapan Indah serta link versi web.</small></article><article><span className="neo-tag neo-blue">PROYEKTOR</span><h3>Link klasemen</h3><p>Menampilkan klasemen baca-saja, pencarian peserta, medali, serta riwayat skor dan poin setiap babak.</p><div className="neo-guide-url">/k/260917-143205</div><span className="neo-guide-demo-button">Lihat klasemen ↗</span><small>Data diperbarui otomatis setiap 30 detik dan dapat diperiksa peserta.</small></article></div></section>

    <section className="neo-guide-finish"><span className="neo-eyebrow">SIAP MENJALANKAN TURNAMEN?</span><h2>Mulai dari format pertandingan, lalu ikuti status di dashboard.</h2><p>Sistem membantu pencatatan dan perhitungan. Keputusan khusus di lapangan—misalnya walkout, diskualifikasi, atau pertandingan dihentikan—tetap ditetapkan oleh panitia sebelum hasil dimasukkan.</p><div className="neo-actions"><Link className="neo-button neo-dark" href="/tournaments/new">+ Buat turnamen</Link><Link className="neo-button neo-secondary" href="/tournaments">Kembali ke daftar</Link></div></section>
  </>;
}
